# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `async-process` gem.
# Please instead update this file by running `bin/tapioca gem async-process`.

# source://async-process//lib/async/process/version.rb#21
module Async; end

# source://async-process//lib/async/process/version.rb#22
module Async::Process
  class << self
    # source://async-process//lib/async/process.rb#33
    def capture(*arguments, **options); end

    # source://async-process//lib/async/process.rb#29
    def spawn(*arguments, **options); end
  end
end

# source://async-process//lib/async/process/child.rb#25
class Async::Process::Child
  # @return [Child] a new instance of Child
  #
  # source://async-process//lib/async/process/child.rb#26
  def initialize(*args, **options); end

  # source://async-process//lib/async/process/child.rb#48
  def kill(signal = T.unsafe(nil)); end

  # Returns the value of attribute pid.
  #
  # source://async-process//lib/async/process/child.rb#42
  def pid; end

  # @return [Boolean]
  #
  # source://async-process//lib/async/process/child.rb#44
  def running?; end

  # source://async-process//lib/async/process/child.rb#52
  def wait; end

  private

  # source://async-process//lib/async/process/child.rb#62
  def wait_thread; end
end

# source://async-process//lib/async/process/version.rb#23
Async::Process::VERSION = T.let(T.unsafe(nil), String)
