# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `neo4j-ruby-driver` gem.
# Please instead update this file by running `bin/tapioca gem neo4j-ruby-driver`.

# THIS IS AN EMPTY RBI FILE.
# see https://github.com/Shopify/tapioca#manually-requiring-parts-of-a-gem
