version: "3.8"

services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bin/dev
    volumes:
      - .:/app
      - bundle_cache:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT=true
      - PORT=3000

  redis:
    image: redis:latest

volumes:
  bundle_cache:
