version: "3.8"

services:
  app:
    stdin_open: true
    command: bin/dev
    build:
      context: .
      args:
        RAILS_ENV: development
      network: host
    volumes:
      - .:/app
      - bundle_cache:/bundle
      - code:/app/tmp/code
    ports:
      - "3000:3000"
      - "3036:3036"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
      - RAILS_LOG_TO_STDOUT="1"
      - PORT=3000
      - BUNDLE_PATH=/bundle
      - OTEL_EXPORTER_OTLP_ENDPOINT="https://api.honeycomb.io"
      - OTEL_EXPORTER_OTLP_HEADERS="x-honeycomb-team=9RxFmtVYWUsAI9nvcnUXhC"
      - OTEL_SERVICE_NAME="deckhand"

  redis:
    image: redis:latest

volumes:
  bundle_cache:
  code:
