# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Deckhand::Tools; end
module Deckhand::Tools::Tool; end
module ImproveUndocumentedFilesAgent::FILE_EXTENSIONS_QUESTION; end
module ListFilesTool::ToolError; end
module RedisStack::ActiveGraph::Core::Query; end
module ShellTask::TASKS_DIR; end
